

#jar
dest.file=./Mama.jar


#src
src=src
src.main.lab=${src}/main/java/itmo/lab/web4
test.src=src/main/test/java
test.reports.dir=${build}/test-reports
test.classes.dir=${build}/test-classes
fatlib.dir=${build}/fatlib
lib.dir=${target.dependency}
resources.dir=${src}/main/resources
native2ascii.resources=${resources.dir}/native2ascii
# Alternative build settings
alt.src.dir=${build}/alt-src
#manifest
manifest.value=itmo.lab.web4.Web4Application

alt.user.regex=/login
alt.user=comeinside

target=target
target.dependency=${target}/dependency


build=build
build.classes=${build}/classes
