<?xml version="1.0" encoding="UTF-8"?>

<project name="lab4" default="build">

    <property file="build.properties"/>

    <path id="project.classpath">
        <fileset dir="${lib.dir}">
            <include name="**/*.jar"/>
        </fileset>
    </path>

    <target name="init">
        <exec executable="mvn" failonerror="true">
            <arg value="dependency:copy-dependencies"/>
        </exec>

        <mkdir dir="${build}"/>
        <mkdir dir="${build.classes}"/>
    </target>

    <target name="compile" depends="init">
        <javac
                srcdir="${src}"
                destdir="${build.classes}"
                classpathref="project.classpath"
                nowarn="on"
        />

        <copy todir="${build.classes}">
            <fileset dir="src/main/resources"/>
        </copy>
    </target>

    <target name="build" depends="compile, xml">
        <mkdir dir="${fatlib.dir}"/>
        <unzip dest="${fatlib.dir}">
            <fileset dir="${lib.dir}" includes="*.jar"/>
        </unzip>

        <jar destfile="${dest.file}">
            <fileset dir="${build.classes}"/>
            <fileset dir="${fatlib.dir}"/>
            <manifest>
                <attribute name="Main-Class" value="itmo.lab.web4.Web4Application"/>
            </manifest>
        </jar>
    </target>

    <target name="clean">
        <delete dir="${build}"/>
    </target>


    <target name="xml">
        <xmlvalidate file="pom.xml" lenient="yes"/>
    </target>

    <target name="test" depends="compile">
        <mkdir dir="${test.classes.dir}"/>

        <javac
                srcdir="${test.src}"
                destdir="${test.classes.dir}"
                classpathref="project.classpath"
                nowarn="on"
                includeantruntime="false"
        >
            <classpath>
                <pathelement path="${build.classes}"/>
            </classpath>
        </javac>

        <junit printsummary="yes" haltonfailure="no">
            <classpath>
                <path refid="project.classpath"/>
                <pathelement path="${build.classes}"/>
                <pathelement path="${test.classes.dir}"/>
            </classpath>

            <formatter type="plain" usefile="false"/>
            <formatter type="xml"/>

            <batchtest todir="${build}/test-reports">
                <fileset dir="${test.src}">
                    <include name="**/*Test*.java"/>
                </fileset>
            </batchtest>
        </junit>
    </target>

    <target name="native2ascii"/>
    <target name="music"/>
    <target name="team"/>
    <target name="alt"/>
    <target name="env"/>

</project>