

#jar
dest.file=./Mama.jar


#src
src=src
src.main.lab=${src}/main/java/itmo/lab/web4
web.dir=${src}/main/webapp

#manifest
manifest.value=itmo.lab.web4.Web4Application


target=target
target.dependency=${target}/dependency


build=build
build.classes=${build}/classes
