

#jar
dest.file=Mama.jar

dest.dir=zips
#src
src=src
src.main.lab=${src}/main/java/itmo/lab/web4
test.src=src/main/test/java
test.reports.dir=${build}/test-reports
test.classes.dir=${build}/test-classes
fatlib.dir=${build}/fatlib
lib.dir=${target.dependency}
resources.dir=${src}/main/resources
native2ascii.resources=${resources.dir}/native2ascii
# Alternative build settings
alt.src.dir=${build}/alt-src
#manifest
manifest.value=itmo.lab.web4.Web4Application
revisions.dir=revisions
revisions.dir.revision1=${revisions.dir}/revision1
revisions.dir.revision1.src=${revisions.dir.revision1}/src
revisions.dir.revision2.src=${revisions.dir.revision2}/src
revisions.dir.revision1.libs=${revisions.dir.revision1}/target/dependency
revisions.dir.revision2=${revisions.dir}/revision2
revisions.dir.revision2.libs=${revisions.dir.revision2}/target/dependency
dist=dist
output.zip=${dist}/revisions.zip
local.svn.repo=file:///Users/montana/MyLabs/OPI/OPI_Lab2/Repository2005

alt.user.regex=/login
alt.user=comeinside

target=target
target.dependency=${target}/dependency


build=build
build.classes=${build}/classes
